name: Cypress Tests

on: [push]

# This configuration is largely from the Cypress dashboard.
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir:
          - packages/next
          - packages/sanity-next

    steps:

      - name: Install
        uses: bkwld/cloak-actions/install@v1

      - name: Build chunks
        run: yarn build

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          install: false
          working-directory: ${{ matrix.dir }}
          component: true
          record: true
        env:
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
